name: Build and Publish Docker image to GHCR

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repo name
        id: repo
        run: |
          echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Generate date and time strings
        id: dates
        run: |
          now=$(date '+%s')
          echo "DATE_VAR=$(date -u -d "@$now" '+%Y-%m-%d')" >> $GITHUB_ENV
          echo "DATE_TIME_VAR=$(date -u -d "@$now" '+%Y-%m-%d.%H-%M-%S')" >> $GITHUB_ENV
          year_month=$(date -u -d "@$now" '+%Y-%m')
          echo "SOURCE_DATE_EPOCH_VAR=$(date -u -d "${year_month}-01 00:00:00" '+%s')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./server
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LC }}:latest
            ghcr.io/${{ env.REPO_LC }}:${{ env.DATE_VAR }}
            ghcr.io/${{ env.REPO_LC }}:${{ env.DATE_TIME_VAR }}
            ghcr.io/${{ env.REPO_LC }}:${{ github.sha }}
            ghcr.io/${{ env.REPO_LC }}:${{ github.sha }}.${{ env.DATE_VAR }}
            ghcr.io/${{ env.REPO_LC }}:${{ github.sha }}.${{ env.DATE_TIME_VAR }}
          build-args: |
            SOURCE_DATE_EPOCH=${{ env.SOURCE_DATE_EPOCH_VAR }}
          outputs: "type=registry,compression=zstd,force-compression=true,compression-level=3,rewrite-timestamp=true,oci-mediatypes=true"
