name: Build and Publish Docker image to GHCR

on:
  push:
    branches: [main]

jobs:
  set-env:
    runs-on: ubuntu-24.04
    outputs:
      DOCKER_IMAGE_NAME: ${{ steps.env_vars.outputs.DOCKER_IMAGE_NAME }}
      SHA_VAR: ${{ steps.env_vars.outputs.SHA_VAR }}
      DATE_VAR: ${{ steps.dates.outputs.DATE_VAR }}
      DATE_TIME_VAR: ${{ steps.dates.outputs.DATE_TIME_VAR }}
      SOURCE_DATE_EPOCH_VAR: ${{ steps.dates.outputs.SOURCE_DATE_EPOCH_VAR }}
    steps:
      - name: Set repository name and SHA
        id: env_vars
        run: |
          echo "DOCKER_IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT
          echo "SHA_VAR=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Generate date and time strings
        id: dates
        run: |
          now=$(date '+%s')
          echo "DATE_VAR=$(date -u -d "@$now" '+%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "DATE_TIME_VAR=$(date -u -d "@$now" '+%Y-%m-%d.%H-%M-%S')" >> $GITHUB_OUTPUT
          year_month=$(date -u -d "@$now" '+%Y-%m')
          echo "SOURCE_DATE_EPOCH_VAR=$(date -u -d "${year_month}-01 00:00:00" '+%s')" >> $GITHUB_OUTPUT

  build-and-push:
    needs: set-env
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-24.04
            variant_suffix: amd64
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
            variant_suffix: arm64
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        env:
          SOURCE_DATE_EPOCH: ${{ needs.set-env.outputs.SOURCE_DATE_EPOCH_VAR }}
        with:
          context: ./server
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ${{ needs.set-env.outputs.DOCKER_IMAGE_NAME }}:latest.${{ matrix.variant_suffix }}
            ${{ needs.set-env.outputs.DOCKER_IMAGE_NAME }}:${{ needs.set-env.outputs.DATE_VAR }}.${{ matrix.variant_suffix }}
            ${{ needs.set-env.outputs.DOCKER_IMAGE_NAME }}:${{ needs.set-env.outputs.DATE_TIME_VAR }}.${{ matrix.variant_suffix }}
            ${{ needs.set-env.outputs.DOCKER_IMAGE_NAME }}:${{ needs.set-env.outputs.SHA_VAR }}.${{ matrix.variant_suffix }}
            ${{ needs.set-env.outputs.DOCKER_IMAGE_NAME }}:${{ needs.set-env.outputs.SHA_VAR }}.${{ needs.set-env.outputs.DATE_VAR }}.${{ matrix.variant_suffix }}
            ${{ needs.set-env.outputs.DOCKER_IMAGE_NAME }}:${{ needs.set-env.outputs.SHA_VAR }}.${{ needs.set-env.outputs.DATE_TIME_VAR }}.${{ matrix.variant_suffix }}
          outputs: "type=registry,compression=zstd,force-compression=true,compression-level=3,rewrite-timestamp=true,oci-mediatypes=true"

  create-manifest:
    runs-on: ubuntu-24.04
    needs: [set-env, build-and-push]
    permissions:
      packages: write
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push manifest list
        env:
          DOCKER_IMAGE_NAME: ${{ needs.set-env.outputs.DOCKER_IMAGE_NAME }}
          DATE_VAR: ${{ needs.set-env.outputs.DATE_VAR }}
          DATE_TIME_VAR: ${{ needs.set-env.outputs.DATE_TIME_VAR }}
          SHA_VAR: ${{ needs.set-env.outputs.SHA_VAR }}
        run: |
          TAGS=(
            "latest"
            "${DATE_VAR}"
            "${DATE_TIME_VAR}"
            "${SHA_VAR}"
            "${SHA_VAR}.${DATE_VAR}"
            "${SHA_VAR}.${DATE_TIME_VAR}"
          )

          for tag in "${TAGS[@]}"; do
            echo "Processing tag: ${tag}"
            docker manifest create ${DOCKER_IMAGE_NAME}:${tag} \
              ${DOCKER_IMAGE_NAME}:${tag}.amd64 \
              ${DOCKER_IMAGE_NAME}:${tag}.arm64
            docker manifest push ${DOCKER_IMAGE_NAME}:${tag}
          done
