name: Build and Publish Docker image to GHCR

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-24.04
            arch_suffix: amd64
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
            arch_suffix: arm64
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repo name
        id: repo
        run: |
          echo "DOCKER_IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Generate date and time strings
        id: dates
        run: |
          now=$(date '+%s')
          echo "DATE_VAR=$(date -u -d "@$now" '+%Y-%m-%d')" >> $GITHUB_ENV
          echo "DATE_TIME_VAR=$(date -u -d "@$now" '+%Y-%m-%d.%H-%M-%S')" >> $GITHUB_ENV
          year_month=$(date -u -d "@$now" '+%Y-%m')
          echo "SOURCE_DATE_EPOCH_VAR=$(date -u -d "${year_month}-01 00:00:00" '+%s')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./server
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:latest.${{ matrix.arch_suffix }}
            ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DATE_VAR }}.${{ matrix.arch_suffix }}
            ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DATE_TIME_VAR }}.${{ matrix.arch_suffix }}
            ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}.${{ matrix.arch_suffix }}
            ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}.${{ env.DATE_VAR }}.${{ matrix.arch_suffix }}
            ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}.${{ env.DATE_TIME_VAR }}.${{ matrix.arch_suffix }}
          build-args: |
            SOURCE_DATE_EPOCH=${{ env.SOURCE_DATE_EPOCH_VAR }}
          outputs: "type=registry,compression=zstd,force-compression=true,compression-level=3,rewrite-timestamp=true,oci-mediatypes=true"

  create-manifest:
    runs-on: ubuntu-24.04
    needs: build-and-push
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repo name
        id: repo
        run: |
          echo "DOCKER_IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Generate date and time strings
        id: dates
        run: |
          now=$(date '+%s')
          echo "DATE_VAR=$(date -u -d "@$now" '+%Y-%m-%d')" >> $GITHUB_ENV
          echo "DATE_TIME_VAR=$(date -u -d "@$now" '+%Y-%m-%d.%H-%M-%S')" >> $GITHUB_ENV

      - name: Create and push manifest list
        run: |
          TAGS=(
            "latest"
            "${{ env.DATE_VAR }}"
            "${{ env.DATE_TIME_VAR }}"
            "${{ github.sha }}"
            "${{ github.sha }}.${{ env.DATE_VAR }}"
            "${{ github.sha }}.${{ env.DATE_TIME_VAR }}"
          )

          for tag in "${TAGS[@]}"; do
            echo "Processing tag: ${tag}"
            docker manifest create ${{ env.DOCKER_IMAGE_NAME }}:${tag} \
              ${{ env.DOCKER_IMAGE_NAME }}:${tag}.amd64 \
              ${{ env.DOCKER_IMAGE_NAME }}:${tag}.arm64
            docker manifest push ${{ env.DOCKER_IMAGE_NAME }}:${tag}
          done
